language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

git:
  depth: 10

before_install:
  - chmod +x gradlew
  - sudo pip install codecov
  
after_success:
  - ./gradlew jacocoTestReport coveralls
  - codecov
