language: java

jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7

env:
  - TERM=dumb

git:
  depth: 10

before_install:
  - chmod +x gradlew
  
after_success:
  - ./gradlew jacocoTestReport coveralls